name: Snowflake Pipeline

on:
  push:
    branches: [main]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash -o snowsql.sh
          bash snowsql.sh -y
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify SnowSQL
        run: snowsql -v

      - name: Run Setup
        run: snowsql -f sql/01_setup.sql
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Load Data
        run: snowsql -f sql/02_load_data.sql
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Transform
        run: snowsql -f sql/03_transform.sql
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Streams & Tasks
        run: snowsql -f sql/04_streams_tasks.sql
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Stored Procedure
        run: snowsql -f sql/05_procedure.sql
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
